<a href="https://colab.research.google.com/github/LuxorLu/LuxorLu/blob/main/Coffee_Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Yaroslav Isaienkov. (2025). Coffee Sales [Dataset]. Kaggle. https://doi.org/10.34740/KAGGLE/DSV/11159944

In [2]:
import pandas as pd

# завантажуємо файл у таблицю (DataFrame)
df = pd.read_csv('index_1.csv')

# показуємо перші 5 рядків
df.head()

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [3]:
# подивимося на загальну інформацію про колонки та типи даних
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   object
 1   datetime     3636 non-null   object
 2   cash_type    3636 non-null   object
 3   card         3547 non-null   object
 4   money        3636 non-null   float64
 5   coffee_name  3636 non-null   object
dtypes: float64(1), object(5)
memory usage: 170.6+ KB

In [4]:
# перетворюємо колонку 'datetime' у формат дати й часу
df['datetime'] = pd.to_datetime(df['datetime'])

# перетворюємо колонку 'date' у формат дати
df['date'] = pd.to_datetime(df['date'])

# перевіряємо типи даних
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   datetime64[ns]
 1   datetime     3636 non-null   datetime64[ns]
 2   cash_type    3636 non-null   object
 3   card         3547 non-null   object
 4   money        3636 non-null   float64
 5   coffee_name  3636 non-null   object
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 170.6+ KB

Наступний етап це перевірити чи повні дані. Почнемо з перевірки пустих колонок та пропусків.

In [5]:
# перевіряємо кількість пропусків у кожній колонці

df.isnull().sum()

date            0
datetime        0
cash_type       0
card           89
money           0
coffee_name     0
dtype: int64

In [6]:
# вибираємо тільки ті замовлення, де в колонці 'card' стоїть пропуск
missing_cards = df[df['card'].isna()]

# показуємо, які типи оплати (cash_type) були у цих 89 замовленнях
missing_cards['cash_type'].value_counts()

cash_type
cash    89
Name: count, dtype: int64

Перевірили пусті значення у колонці 'card', виявили що 89 пропусків це оплата готівкою. Тому немає даних в колонці 'card'. Натупний етап це заповнити пропуски значенням 'no card'.

In [8]:
# pаповнюємо порожні клітинки в колонці 'card' текстом 'no card'
df['card'] = df['card'].fillna('no card')

# Перевіряємо пропуски ще раз
df.isnull().sum()

date           0
datetime       0
cash_type      0
card           0
money          0
coffee_name    0
dtype: int64

Переходимо до перевірки повноти даних. А саме до дати, перевіримо часову цілісність.

In [9]:
min_date = df['date'].min()
max_date = df['date'].max()

print("Початок даних:", min_date)
print("Кінець даних:", max_date)

Початок даних: 2024-03-01 00:00:00
Кінець даних: 2025-03-23 00:00:00

In [10]:
# Групуємо продажі по місяцях і рахуємо робочі дні та кількість замовлень
df.groupby(df['date'].dt.to_period('M')).agg(
    днів_з_продажами=('date', 'nunique'),
    всього_замовлень=('date', 'count'),
    перший_день=('date', 'min'),
    останній_день=('date', 'max')
)

         днів_з_продажами  всього_замовлень перший_день останній_день
date
2024-03                31               206  2024-03-01    2024-03-31
2024-04                30               196  2024-04-01    2024-04-30
2024-05                28               267  2024-05-02    2024-05-31
2024-06                30               227  2024-06-01    2024-06-30
2024-07                31               237  2024-07-01    2024-07-31
2024-08                31               272  2024-08-01    2024-08-31
2024-09                30               344  2024-09-01    2024-09-30
2024-10                31               426  2024-10-01    2024-10-31
2024-11                29               259  2024-11-01    2024-11-30
2024-12                31               259  2024-12-01    2024-12-31
2025-01                28               201  2025-01-02    2025-01-31
2025-02                28               423  2025-02-01    2025-02-28
2025-03                23               319  2025-03-01    2025-03-23